- README.md
Se ajudar ta ae uns projetos meus.
> Projetos de referência

- README.md
Eu percebi que tinha colocado a descrição errada como se trata de uma tradução acho que deveria ser na descrição somente markdown
> corrigindo tecnologia do projeto tradução hexo

- README.md
Estou retomando meus estudos na área de Web, inclusive encontro-me inscrito no programa de mentoria aqui do CT. Enquanto aguardo ser chamado, estou colocando o que aprendi em meus estudos em alguns projetos. Como não tenho portfólio resolvi pegar alguns projetos de amigos e parentes sem custo nenhum para, além de construir este portfólio, aplicar os conhecimentos do estudo. 
Gostaria de receber **qualquer tipo de feedback para este meu projeto**, e **qualquer tipo de comentário** será muito bem recebido. Aguardo a ajuda do pessoal. Desde já obrigado, Abraço
> Adicionado projeto site Recanto Buffet a lista de links

- README.md
Adicionei os repositórios do backend que estamos criando para o Front-End Brasil
> Adicionando repositórios de eventos do front-end brasil

- README.md
Desde já obrigado pelo espaço e as iniciativas do **Training Center**.
Neste pull adicionei o link para dois repositórios de um projeto  meu chamado doesangue.me, um é a landingpage e outro é o spa sendo feito com Vue.js que irá consumir a API que já está criada pelo menos o básico..
> Adicionando projeto doesangue

- README.md
Projeto com o objetivo de mostrar na prática como testar componentes complexos em React com Jest
> Adicionando projeto react-jest-concepts na lista

- README.md
Conforme recomendado no slack, adicionei o meu projeto a lista.
> Adiciona o projeto arojunior/awesome-feed a lista

- README.md
Oi, eu inseri o Framework que tenho construído e to precisando de uma força. Acho lgl quem puder ajudar! Vlw 🤘
> Inserção do Magic Framework

- README.md
Recriar trechos de musica usando a vibração do celular
> Vibration API

- README.md
Maiores informações: https://github.com/training-center/code-review/issues/7
> Adiciona projeto vspedr/movile-messaging

- README.md
Um projeto com objetivo de permitir contibuições de iniciantes, consistindo em uma lista de informações sobre animais de estimação de dos usuários do GitHub.
A lista ficará disponível em http://vspedr.github.io/developets
> Adiciona projeto DeveloPets

- README.md
The `doesangue` project is suspended and the React + Jest is duplicated.
> Remove unavailable and duplicated repositories

- README.md
Retirei um projeto que estava duplicado("Magic Framework") e coloquei meu projeto na lista
> Add: Zombie

- README.md
Adding Brasilino Project, an Arduino Lib that allows programming in Arduino using simplified functions in PT-BR, and Arduino-Tablature project, a Node Package Module (NPM) that is a Web Scraping script to create an Arduino file that has a guitar tablature in the Tone function form.
> Adding Brasilino && ArduinoTablature

- README.md
Tenho o projeto **Awesome dashboard** que é uma lista de dashboard free que podem ser utilizado, estou adicionando este projeto na lista.
> Adds 'Awesome dashboard' project in list

- README.md
Gerador de Deck, Jogo da Velha, Gerador de Senhas e Portfolio
> Links adicionados

- README.md
Projeto está sempre aberto a contribuições de qualquer tipo: https://github.com/go-chat-bot/bot
> Adiciona go-chat-bot

- README.md
Este PR remove o item duplicado **API de Eventos do Front-End Brasil**.
> Remover item duplicado

- README.md
> removendo duplicados (React + Jest)

- README.md
> delete Biblioteca movile-messaging because it was duplicated in the intermediário projects
